
NKRO_ENABLE = yes
AUTO_SHIT_MODIFIERS = no
AUTO_SHIFT_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
COMMAND_ENABLE = no
ENCODER_ENABLE = no
LEADER_ENABLE = no
LED_MATRIX_ENABLE = no
LED_ENABLE = no
BOOTMAGIC_ENABLE = no
